#!/usr/bin/env bash

cp $1.in $1

uname=`uname`

if [[ "$uname" == 'SunOS' ]]; then
	echo Configuring $1 for OpenSolaris
	sed -i 's/-DflagPOSIX -DflagLINUX/-DflagPOSIX -DflagSOLARIS/' $1
	sed -i 's/-Wl,--gc-sections $(LINKOPTIONS)/$(LINKOPTIONS)/' $1
	sed -i 's/GCC-Gcc-Gui-Linux-Main-Posix-Shared/GCC-Gcc-Gui-Main-Posix-Shared-Solaris/' $1
	sed -i 's/GCC-Gcc-Gui-Linux-Posix-Shared/GCC-Gcc-Gui-Posix-Shared-Solaris/' $1
	sed -i 's/GCC-Gcc-Linux-Main-Posix-Shared/GCC-Gcc-Main-Posix-Shared-Solaris/' $1
	sed -i 's/GCC-Gcc-Linux-Posix-Shared/GCC-Gcc-Posix-Shared-Solaris/' $1
	sed -i 's/$(LIBPATH) -Wl,-O,2 $(LDFLAGS)/$(LIBPATH) $(LDFLAGS)/' $1
	sed -i 's/-lpthread /-lposix4 /' $1
	sed -i 's/-lrt /-lsocket -lnsl /' $1
fi

if [[ "$uname" == 'FreeBSD' ]]; then
	echo Configuring $1 for FreeBSD
	sed -i '' 's/-DflagPOSIX -DflagLINUX/-DflagPOSIX -DflagBSD -DflagFREEBSD/' $1
	sed -i '' 's/-Wl,--gc-sections $(LINKOPTIONS)/$(LINKOPTIONS)/' $1
	sed -i '' 's/GCC-Gcc-Gui-Linux-Main-Posix-Shared/GCC-Bsd-Freebsd-Gcc-Gui-Main-Posix-Shared/' $1
	sed -i '' 's/GCC-Gcc-Gui-Linux-Posix-Shared/GCC-Bsd-Freebsd-Gcc-Gui-Posix-Shared/' $1
	sed -i '' 's/GCC-Gcc-Linux-Main-Posix-Shared/GCC-Bsd-Freebsd-Gcc-Main-Posix-Shared/' $1
	sed -i '' 's/GCC-Gcc-Linux-Posix-Shared/GCC-Bsd-Freebsd-Gcc-Posix-Shared/' $1
	sed -i '' 's/$(LIBPATH) -Wl,-O,2 $(LDFLAGS)/$(LIBPATH) $(LDFLAGS)/' $1
	sed -i '' 's/-ldl /-lexecinfo /' $1
fi

if [[ "$uname" == 'OpenBSD' ]]; then
	echo Configuring $1 for OpenBSD
	sed -i.bak 's/-DflagPOSIX -DflagLINUX/-DflagPOSIX -DflagBSD -DflagOPENBSD/' $1
	sed -i.bak 's/-Wl,--gc-sections $(LINKOPTIONS)/$(LINKOPTIONS)/' $1
	sed -i.bak 's#LIBPATH =#LIBPATH = -L"/usr/local/lib"#' $1
	sed -i.bak 's#-I./ -I$(UPPOUT)#-I/usr/local/include -I./ -I$(UPPOUT)#' $1
	sed -i.bak 's/GCC-Gcc-Gui-Linux-Main-Posix-Shared/GCC-Bsd-Gcc-Gui-Main-Openbsd-Posix-Shared/' $1
	sed -i.bak 's/GCC-Gcc-Gui-Linux-Posix-Shared/GCC-Bsd-Gcc-Gui-Openbsd-Posix-Shared/' $1
	sed -i.bak 's/GCC-Gcc-Linux-Main-Posix-Shared/GCC-Bsd-Gcc-Main-Openbsd-Posix-Shared/' $1
	sed -i.bak 's/GCC-Gcc-Linux-Posix-Shared/GCC-Bsd-Gcc-Openbsd-Posix-Shared/' $1
	sed -i.bak 's/$(LIBPATH) -Wl,-O,2 $(LDFLAGS)/$(LIBPATH) $(LDFLAGS)/' $1
	sed -i.bak 's/-ldl /-lexecinfo /' $1
	sed -i.bak 's/-lrt / /' $1
	rm  $1.bak
fi

if [[ "$uname" == 'NetBSD' ]]; then
	echo Configuring $1 for OpenBSD
	sed -i.bak 's/-DflagPOSIX -DflagLINUX/-DflagPOSIX -DflagBSD -DflagNETBSD/' $1
	sed -i.bak 's/-Wl,--gc-sections $(LINKOPTIONS)/$(LINKOPTIONS)/' $1
	sed -i.bak 's#LIBPATH =#LIBPATH = -L"/usr/local/lib"#' $1
	sed -i.bak 's#-I./ -I$(UPPOUT)#-I/usr/local/include -I./ -I$(UPPOUT)#' $1
	sed -i.bak 's/$(LIBPATH) -Wl,-O,2 $(LDFLAGS)/$(LIBPATH) $(LDFLAGS)/' $1
	sed -i.bak 's/-ldl /-lexecinfo /' $1
	sed -i.bak 's/-lrt / /' $1
	rm  $1.bak
fi

if [[ "$uname" == 'Darwin' ]]; then
	echo Configuring $1 for MacOS
	# sed -i.bak 's/\`pkg-config --cflags libpng\` \`pkg-config --cflags freetype2\` \`pkg-config --cflags x11\` \`pkg-config --cflags fontconfig\` \`pkg-config --cflags xcb\` \`pkg-config --cflags expat\`/ /' $1
	`pkg-config --exists libpng` || sed -i.bak 's/\`pkg-config --cflags libpng\`/ /' $1
	`pkg-config --exists freetype2` || sed -i.bak 's/\`pkg-config --cflags freetype2\`/ /' $1
	`pkg-config --exists x11` || sed -i.bak 's/\`pkg-config --cflags x11\`/ /' $1
	`pkg-config --exists xinerama` || sed -i.bak 's/\`pkg-config --cflags xinerama\`/ /' $1
	`pkg-config --exists xrender` || sed -i.bak 's/\`pkg-config --cflags xrender\`/ /' $1
	`pkg-config --exists xft` || sed -i.bak 's/\`pkg-config --cflags xft\`/ /' $1
	`pkg-config --exists xdmcp` || sed -i.bak 's/\`pkg-config --cflags xdmcp\`/ /' $1
	`pkg-config --exists xext` || sed -i.bak 's/\`pkg-config --cflags xext\`/ /' $1
	`pkg-config --exists gtk+3.0` || sed -i.bak 's/\`pkg-config --cflags gtk+-3.0\`/ /' $1
	`pkg-config --exists libnotify` || sed -i.bak 's/\`pkg-config --cflags libnotify\`/ /' $1
	`pkg-config --exists fontconfig` || sed -i.bak 's/\`pkg-config --cflags fontconfig\`/ /' $1
	`pkg-config --exists xcb` || sed -i.bak 's/\`pkg-config --cflags xcb\`/ /' $1
	`pkg-config --exists expat` || sed -i.bak 's/\`pkg-config --cflags expat\`/ /' $1
	sed -i.bak 's/-Wl,--gc-sections $(LINKOPTIONS)/$(LINKOPTIONS)/' $1
	sed -i.bak 's/$(LINKER) -o "$(OutFile)" -Wl,-s $(LIBPATH) -Wl,-O,2 $(LDFLAGS) -Wl,--start-group/$(LINKER) -o "$(OutFile)" $(LIBPATH) $(LDFLAGS)/' $1
	`pkg-config --exists libpng` || sed -i.bak 's/\`pkg-config --libs libpng\`/ /' $1
	`pkg-config --exists freetype2` || sed -i.bak 's/\`pkg-config --libs freetype2\`/ /' $1
	`pkg-config --exists x11` || sed -i.bak 's/\`pkg-config --libs x11\`/ /' $1
	`pkg-config --exists fontconfig` || sed -i.bak 's/\`pkg-config --libs fontconfig\`/ /' $1
	`pkg-config --exists xcb` || sed -i.bak 's/\`pkg-config --libs xcb\`/ /' $1
	`pkg-config --exists expat` || sed -i.bak 's/\`pkg-config --libs expat\`/ /' $1
	sed -i.bak 's/-lrt / /' $1
	sed -i.bak 's/-Wl,--end-group/ /' $1
fi
